- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/cmd_vel_stamped"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/TwistStamped"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "r1_mini/odom"
  gz_topic_name: "/r1_mini/odom"
  gz_type_name: "ignition.msgs.Odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/joint_states"
  gz_topic_name: "/r1_mini/joint_states"
  gz_type_name: "ignition.msgs.Model"
  ros_type_name: "sensor_msgs/msg/JointState"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf_odom"
  gz_topic_name: "/r1_mini/odom_tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/r1_mini/lidar"
  gz_topic_name: "r1_mini/lidar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS
